import React from "react"
import Layout from '../components/layout'


const textStyle = {
  fontFamily: 'LiberationSans-Regular',
  fontSize: '12px',
  maxWidth: '600px'
}

const heading = {
  fontFamily: 'LiberationSans-Regular',
  fontSize: '20px',
}


export default function About() {
  return (
    <Layout>
      <h1 style={heading}>ABOUT</h1>
      <p style={textStyle}>
        {" "}
        AND SUCH IS A CONSULTING, PRODUCTION, AND PR AGENCY FOUNDED BY KAT
        COOPER AND MARY ANDERSON WHOSE KNOWLEDGE OF LUXURY FASHION, STREET
        CULTURE, EMERGING CREATIVES, AND TOP TALENT INFORMS THEIR ABILITY TO
        HEIGHTEN BRAND VISIBILITY THROUGH TRADITIONAL AND NON TRADITIONAL PRESS,
        CELEBRITY AND INFLUENCER SEEDING, EVENT PRODUCTION, AND CONTENT
        PRODUCTION.THROUGH THEIR CREATIVE LENS, EXTENSIVE NETWORK, AND
        EXPERIENCE IN THE FASHION AND MUSIC INDUSTRIES, THEY’ RE ABLE TO
        POSITION BRANDS IN A FRESH AND EXCITING WAY.{" "}
      </p>
      <p style={textStyle}>
        KAT COOPER WORKED AT AGENCY FACTORY PR IN NYC FOR SEVERAL YEARS BEFORE
        LEADING THE PR DEPARTMENT AT PAPER MAGAZINE FOR TWO YEARS WORKING ON THE
        PUBLICATION AS WELL AS BRANDED ACTIVATIONS AND EVENTS, THEN LATER JOINED
        MOOSE KNUCKLES CANADA.SHE SPENT THE NEXT TWO YEARS BUILDING MOOSE’ S PR
        AND INFLUENCER MARKETING DEPARTMENT, HELPING THE BRAND TO GAIN GLOBAL
        RECOGNITION.IN ADDITION TO HAVING AGENCY AND IN - HOUSE EXPERIENCE, KAT
        HAS FREELANCED IN MANY CAPACITIES FOR BRANDS SUCH AS REFINERY29,
        ALEXANDER WANG, PYER MOSS, LUNYA, SLASHED BY TIA, LAQUAN SMITH, AND BAPE
        TO NAME A FEW.</p>
        <p style={textStyle}> MARY ANDERSON WORKED IN FASHION AND MUSIC ON A FREELANCE
        BASIS BEFORE LEADING VIP AND SPECIAL EVENTS, PR, AND PHOTO PRODUCTION AT
        THE FAMED CAFE HENRIE IN SOHO, NEW YORK CITY.SHE JOINED KAT IN EARLY
        2017 TO SUPPORT PR, CREATIVE PRODUCTION, AND TO LEAD THE INFLUENCER AND
        VIP RELATIONS AT MOOSE KNUCKLES CANADA, WHERE THEY TRANSFORMED A
        RELATIVELY UNKNOWN BRAND INTO ONE OF THE HOTTEST OUTERWEAR LABELS ON THE
        MARKET.IN ADDITION TO HER WORK AT MOOSE KNUCKLES, MARY HAS WORKED
        FREELANCE WITH A VARIETY OF FASHION BRANDS, OFFERING HER EXPERTISE IN
        CREATIVE CONSULTING, EVENT AND PHOTO PRODUCTION, AND CELEBRITY SEEDING.
      </p>
    </Layout>
  )
}
